name: save_heaven
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  syncfusion_flutter_datepicker: ^29.2.5
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  smooth_page_indicator: ^1.2.1
  flutter_launcher_icons: ^0.14.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true
  assets:
      - assets/icons/
      - assets/images/

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
