name: save_heaven
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  syncfusion_flutter_datepicker: ^29.2.5
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  smooth_page_indicator: ^1.2.1
  flutter_launcher_icons: ^0.14.4
  cached_network_image: ^3.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  expandable_text: ^2.3.0
  like_button: ^2.1.0
  intl: ^0.20.2
  dartz: ^0.10.1
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  equatable: ^2.0.7
  firebase_core: ^3.14.0
  firebase_messaging: ^15.2.7
  shimmer: ^3.0.0
  jwt_decoder: ^2.0.1
  flutter_staggered_grid_view: ^0.7.0
  image_picker: ^1.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.15

flutter_launcher_icons:
  android: true
  image_path: "assets/icons/app_icon.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
      - assets/icons/
      - assets/images/

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
